import type { MissionTask } from '@/types/games/mabinogi_mobile/mission';

export const MISSION_TASKS: MissionTask[] = [
  // === 일일 ===
  // 계정 단위
  {
    id: 'daily-cashshop-free',
    title: '캐시샵 매일 무료 상품',
    description: '캐시샵에서 매일 무료 상품 1회 수령',
    type: 'daily',
    scope: 'account',
    maxCompletions: 1,
    category: '캐시샵',
  },
  {
    id: 'daily-gem-chest',
    title: '조각난 보석 보물상자',
    description: '캐시샵-골드 메뉴에서 조각난 보석 보물상자 1회 구매',
    type: 'daily',
    scope: 'account',
    maxCompletions: 1,
    category: '캐시샵',
  },
  // 캐릭터 단위
  {
    id: 'daily-dungeon',
    title: '요일 던전',
    description: '요일별 전용 던전 1회 클리어',
    type: 'daily',
    scope: 'character',
    maxCompletions: 1,
    category: '던전',
  },
  {
    id: 'daily-blackhole',
    title: '검은 구멍',
    description: '검은 구멍 3회 클리어',
    type: 'daily',
    scope: 'character',
    maxCompletions: 3,
    category: '사냥터',
  },
  {
    id: 'daily-summon-barrier',
    title: '불길한 소환의 결계',
    description: '불길한 소환의 결계 2회 클리어 (3시간 간격 입장)',
    type: 'daily',
    scope: 'character',
    maxCompletions: 2,
    category: '사냥터',
  },
  {
    id: 'daily-tower',
    title: '망령의 탑',
    description: '망령의 탑 1회 클리어',
    type: 'daily',
    scope: 'character',
    maxCompletions: 1,
    category: '던전',
  },
  // 사냥터 구역 보스 (늑대의 숲, 여신의 뜰, 얼음협곡) - 통합 카드만 남김
  {
    id: 'daily-huntboss-wolf',
    title: '늑대의 숲 보스',
    description: '늑대의 숲 보스 각 난이도별 1회 처치',
    type: 'daily',
    scope: 'character',
    maxCompletions: 3,
    category: '사냥터',
    difficulties: [
      { key: 'normal', label: '일반', missionId: 'daily-huntboss-wolf-normal' },
      { key: 'hard', label: '어려움', missionId: 'daily-huntboss-wolf-hard' },
      {
        key: 'very',
        label: '매우 어려움',
        missionId: 'daily-huntboss-wolf-very',
      },
    ],
    // UI에는 이 통합 카드만 노출, 난이도별 미션은 숨김 처리
  },
  {
    id: 'daily-huntboss-goddess',
    title: '여신의 뜰 보스',
    description: '여신의 뜰 보스 각 난이도별 1회 처치',
    type: 'daily',
    scope: 'character',
    maxCompletions: 3,
    category: '사냥터',
    difficulties: [
      {
        key: 'normal',
        label: '일반',
        missionId: 'daily-huntboss-goddess-normal',
      },
      {
        key: 'hard',
        label: '어려움',
        missionId: 'daily-huntboss-goddess-hard',
      },
      {
        key: 'very',
        label: '매우 어려움',
        missionId: 'daily-huntboss-goddess-very',
      },
    ],
    // UI에는 이 통합 카드만 노출
  },
  {
    id: 'daily-huntboss-ice',
    title: '얼음협곡 보스',
    description: '얼음협곡 보스 각 난이도별 1회 처치',
    type: 'daily',
    scope: 'character',
    maxCompletions: 3,
    category: '사냥터',
    difficulties: [
      { key: 'normal', label: '일반', missionId: 'daily-huntboss-ice-normal' },
      { key: 'hard', label: '어려움', missionId: 'daily-huntboss-ice-hard' },
      {
        key: 'very',
        label: '매우 어려움',
        missionId: 'daily-huntboss-ice-very',
      },
    ],
    // UI에는 이 통합 카드만 노출
  },

  // === 주간 ===
  {
    id: 'weekly-fieldboss-peri',
    title: '필드보스 - 페리',
    description: '필드보스 페리 1회 처치',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '사냥터',
  },
  {
    id: 'weekly-fieldboss-krab',
    title: '필드보스 - 크라브바흐',
    description: '필드보스 크라브바흐 1회 처치',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '사냥터',
  },
  {
    id: 'weekly-fieldboss-krama',
    title: '필드보스 - 크라마',
    description: '필드보스 크라마 1회 처치',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '사냥터',
  },
  {
    id: 'weekly-token-exchange',
    title: '마물 퇴치증표 교환',
    description: '티르코네일, 던바튼, 콜헨에서 마물 퇴치증표 1회 교환',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '교환',
  },
  {
    id: 'weekly-raid-glass',
    title: '레이드 - 글라스 기브넨',
    description: '레이드(입문) 글라스 기브넨 1회 클리어',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '레이드',
  },
  {
    id: 'weekly-abyss-ruin',
    title: '어비스 던전 - 가라앉은 유적',
    description: '어비스 던전 가라앉은 유적 1회 클리어',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '던전',
  },
  {
    id: 'weekly-abyss-altar',
    title: '어비스 던전 - 무너진 제단',
    description: '어비스 던전 무너진 제단 1회 클리어',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '던전',
  },
  {
    id: 'weekly-abyss-hall',
    title: '어비스 던전 - 파멸의 전당',
    description: '어비스 던전 파멸의 전당 1회 클리어',
    type: 'weekly',
    scope: 'character',
    maxCompletions: 1,
    category: '던전',
  },
];
